version: '3'

services:
  api:
    container_name: apibdb
    restart: always
    build: .
    ports:
      - "8080:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27018:27017"
